import { CinemaScreen, Region, Language } from './types';

export const REGIONS: { id: Region; label: string; labelEn: string }[] = [
  { id: 'North', label: '北區/宜蘭/桃竹苗', labelEn: 'North / Yilan / Taoyuan / Hsinchu' },
  { id: 'Central', label: '中區/彰化', labelEn: 'Central / Changhua' },
  { id: 'South', label: '南區/高雄', labelEn: 'South / Kaohsiung' },
  { id: 'East', label: '東區/外島', labelEn: 'East / Islands' },
  { id: 'Historical', label: '歷史資料 (已歇業/改裝前)', labelEn: 'Historical (Closed/Renovated)' },
];

export const UI_TEXT: Record<string, Record<Language, string>> = {
  appTitle: {
    zh: '台灣影廳大銀幕尺寸比一比',
    en: 'Taiwan Cinema Screen Size',
  },
  selectRegion: {
    zh: '請於選單選擇區域',
    en: 'Please select a region from the menu',
  },
  regionsLabel: {
    zh: '區域',
    en: 'REGIONS',
  },
  searchPlaceholder: {
    zh: '搜尋影廳名稱、地點...',
    en: 'Search cinema, location...',
  },
  sortByArea: {
    zh: '依面積排序',
    en: 'Sort by Area',
  },
  sortByWidth: {
    zh: '依寬度排序',
    en: 'Sort by Width',
  },
  sortByHeight: {
    zh: '依高度排序',
    en: 'Sort by Height',
  },
  tableView: {
    zh: '列表檢視',
    en: 'Table View',
  },
  cardView: {
    zh: '卡片檢視',
    en: 'Card View',
  },
  noRegions: {
    zh: '無符合條件的影廳',
    en: 'No cinemas match your criteria',
  },
  disclaimer: {
    zh: '*標記為特殊規格或官方宣稱',
    en: '*Marked as special spec or official claim',
  },
  source: {
    zh: '資料來源：',
    en: 'Source: ',
  },
  humanLabel: {
    zh: '1.75m 人類',
    en: '1.75m Human',
  },
  clickHint: {
    zh: '點擊可選取',
    en: 'Click to highlight',
  },
  scalePrefix: {
    zh: '比例尺: 1 格 = ',
    en: 'Scale: 1 grid = ',
  },
  meters: {
    zh: '公尺',
    en: 'meters',
  },
  colCinema: {
    zh: '影廳',
    en: 'Cinema',
  },
  colSize: {
    zh: '尺寸',
    en: 'Size',
  },
  colArea: {
    zh: '面積',
    en: 'Area',
  },
};

export const SCREEN_DATA: CinemaScreen[] = [
  // --- North (Taipei, New Taipei, Keelung, Yilan, Taoyuan, Hsinchu) ---
  {
    id: 'n-01',
    name: '國立海洋科技博物館',
    nameEn: 'NMMST (Marine Science Museum)',
    type: '8K投影機*',
    typeEn: '8K Projector*',
    audio: '-',
    width: 29.00,
    height: 22.00,
    area: 638,
    location: 'Keelung',
    locationZh: '基隆',
    region: 'North'
  },
  {
    id: 'n-02',
    name: '台北美麗華大直',
    nameEn: 'Taipei Miramar Cinemas',
    type: 'IMAX(雷射)',
    typeEn: 'IMAX (Laser)',
    audio: 'IMAX 12.1',
    width: 28.40,
    height: 21.20,
    area: 602.08,
    location: 'Taipei',
    locationZh: '台北',
    region: 'North'
  },
  {
    id: 'n-03',
    name: '台北國賓大戲院',
    nameEn: 'Ambassador Theatres (Ximending)',
    type: '鉅院廳(雷射)*',
    typeEn: 'Grand Auditorium (Laser)*',
    audio: 'Dolby Atmos',
    width: 22.00,
    height: 12.00,
    area: 264,
    location: 'Taipei',
    locationZh: '台北',
    region: 'North'
  },
  {
    id: 'n-04',
    name: '台北松仁威秀',
    nameEn: 'MUVIE CINEMAS',
    type: 'TITAN(雷射)*',
    typeEn: 'TITAN (Laser)*',
    audio: 'Dolby 7.1',
    width: 22.00,
    height: 12.00,
    area: 264,
    location: 'Taipei',
    locationZh: '台北',
    region: 'North'
  },
  {
    id: 'n-05',
    name: '新北新店裕隆城威秀',
    nameEn: 'Vieshow Cinemas Xindian Yulon City',
    type: 'IMAX(雷射)*',
    typeEn: 'IMAX (Laser)*',
    audio: '-',
    width: 21.40,
    height: 11.60,
    area: 248.24,
    location: 'New Taipei',
    locationZh: '新北',
    region: 'North'
  },
  {
    id: 'n-06',
    name: '新北板橋大遠百威秀',
    nameEn: 'Vieshow Cinemas Banqiao Mega City',
    type: 'IMAX(雷射)*',
    typeEn: 'IMAX (Laser)*',
    audio: '-',
    width: 21.30,
    height: 11.50,
    area: 244.95,
    location: 'New Taipei',
    locationZh: '新北',
    region: 'North'
  },
  {
    id: 'n-07',
    name: '台北樂聲',
    nameEn: 'Lux Cinema',
    type: '巨幕廳(雷射)',
    typeEn: 'Giant Screen (Laser)',
    audio: 'Dolby 7.1',
    width: 20.00,
    height: 10.00,
    area: 200,
    location: 'Taipei',
    locationZh: '台北',
    region: 'North'
  },
  {
    id: 'n-08',
    name: '台北西門in89',
    nameEn: 'in89 Cinemax Ximen',
    type: 'LUXE*',
    typeEn: 'LUXE*',
    audio: 'Dolby 7.1',
    width: 19.30,
    height: 8.30,
    area: 160.19,
    location: 'Taipei',
    locationZh: '台北',
    region: 'North'
  },
  {
    id: 'n-09',
    name: '台北美麗華大直',
    nameEn: 'Taipei Miramar Cinemas',
    type: 'Dolby Cinema',
    typeEn: 'Dolby Cinema',
    audio: 'Dolby Atmos',
    width: 14.80,
    height: 7.00,
    area: 103.60,
    location: 'Taipei',
    locationZh: '台北',
    region: 'North'
  },
  {
    id: 't-01',
    name: '桃園新光影城',
    nameEn: 'Shin Kong Cinemas Taoyuan',
    type: 'Dolby Cinema*',
    typeEn: 'Dolby Cinema*',
    audio: 'Dolby Atmos',
    width: 20.00,
    height: 10.00,
    area: 200.00,
    location: 'Taoyuan',
    locationZh: '桃園',
    region: 'North'
  },
  {
    id: 't-02',
    name: '桃園美麗新台茂',
    nameEn: 'Miranew Cinemas TaiMall',
    type: 'IMAX',
    typeEn: 'IMAX',
    audio: '-',
    width: 17.80,
    height: 9.80,
    area: 174.44,
    location: 'Taoyuan',
    locationZh: '桃園',
    region: 'North'
  },
  {
    id: 't-03',
    name: '新竹巨城威秀',
    nameEn: 'Vieshow Cinemas Hsinchu Big City',
    type: 'IMAX',
    typeEn: 'IMAX',
    audio: '-',
    width: 17.80,
    height: 9.70,
    area: 172.66,
    location: 'Hsinchu',
    locationZh: '新竹',
    region: 'North'
  },
  {
    id: 't-04',
    name: '桃園新光影城',
    nameEn: 'Shin Kong Cinemas Taoyuan',
    type: 'LUXE',
    typeEn: 'LUXE',
    audio: 'Dolby Atmos',
    width: 17.00,
    height: 7.00,
    area: 119.00,
    location: 'Taoyuan',
    locationZh: '桃園',
    region: 'North'
  },

  // --- Central (Taichung, Changhua) ---
  {
    id: 'c-01',
    name: '台中大遠百威秀',
    nameEn: 'Vieshow Cinemas Taichung Top City',
    type: 'IMAX',
    typeEn: 'IMAX',
    audio: '-',
    width: 18.30,
    height: 9.40,
    area: 172.02,
    location: 'Taichung',
    locationZh: '台中',
    region: 'Central'
  },
  {
    id: 'c-02',
    name: '台中文心秀泰',
    nameEn: 'Showtime Cinemas Wenxin',
    type: '11廳*',
    typeEn: 'Hall 11*',
    audio: 'Dolby Atmos',
    width: 14.00,
    height: 7.00,
    area: 98.00,
    location: 'Taichung',
    locationZh: '台中',
    region: 'Central'
  },

  // --- South (Tainan, Chiayi, Kaohsiung) ---
  {
    id: 's-01',
    name: '台南南紡威秀',
    nameEn: 'Vieshow Cinemas T.S. Mall',
    type: 'IMAX',
    typeEn: 'IMAX',
    audio: '-',
    width: 21.80,
    height: 12.20,
    area: 265.96,
    location: 'Tainan',
    locationZh: '台南',
    region: 'South'
  },
  {
    id: 's-02',
    name: '嘉義in89豪華影城',
    nameEn: 'in89 Luxe Cinemas Chiayi',
    type: 'IMAX(雷射)',
    typeEn: 'IMAX (Laser)',
    audio: 'IMAX 12.1',
    width: 21.50,
    height: 12.30,
    area: 264.45,
    location: 'Chiayi',
    locationZh: '嘉義',
    region: 'South'
  },
  {
    id: 's-03',
    name: '嘉義in89豪華影城',
    nameEn: 'in89 Luxe Cinemas Chiayi',
    type: 'LUXE',
    typeEn: 'LUXE',
    audio: 'Dolby Atmos',
    width: 20.50,
    height: 10.50,
    area: 215.25,
    location: 'Chiayi',
    locationZh: '嘉義',
    region: 'South'
  },
  {
    id: 's-04',
    name: '高雄義大國賓',
    nameEn: 'Ambassador Theatres E-Da',
    type: '8廳',
    typeEn: 'Hall 8',
    audio: 'Dolby 7.1',
    width: 20.00,
    height: 8.00,
    area: 160,
    location: 'Kaohsiung',
    locationZh: '高雄',
    region: 'South'
  },
  {
    id: 's-05',
    name: '高雄夢時代秀泰',
    nameEn: 'Showtime Cinemas Dream Mall',
    type: '巨幕廳(雷射)',
    typeEn: 'Giant Screen (Laser)',
    audio: 'Dolby 7.1',
    width: 19.00,
    height: 8.14,
    area: 154.71,
    location: 'Kaohsiung',
    locationZh: '高雄',
    region: 'South'
  },
  {
    id: 's-06',
    name: '高雄大遠百威秀',
    nameEn: 'Vieshow Cinemas Kaohsiung FE21',
    type: 'IMAX(雷射)*',
    typeEn: 'IMAX (Laser)*',
    audio: '-',
    width: 15.90,
    height: 8.20,
    area: 130.38,
    location: 'Kaohsiung',
    locationZh: '高雄',
    region: 'South'
  },
  {
    id: 's-07',
    name: '台南國賓',
    nameEn: 'Ambassador Theatres Tainan',
    type: 'A廳',
    typeEn: 'Hall A',
    audio: 'Dolby 7.1',
    width: 15.50,
    height: 6.60,
    area: 102.3,
    location: 'Tainan',
    locationZh: '台南',
    region: 'South'
  },

  // --- East / Islands ---
  {
    id: 'e-01',
    name: '花蓮新天堂樂園威秀',
    nameEn: 'Vieshow Cinemas Hualien Paradiso',
    type: 'IMAX(雷射)*',
    typeEn: 'IMAX (Laser)*',
    audio: 'IMAX 12.1',
    width: 21.30,
    height: 12.00,
    area: 255.6,
    location: 'Hualien',
    locationZh: '花蓮',
    region: 'East'
  },
  {
    id: 'e-02',
    name: '金門金獅',
    nameEn: 'Golden Lion Cinemax',
    type: '4D+ 影廳(A廳)*',
    typeEn: '4D+ Hall (Hall A)*',
    audio: 'Dolby Atmos',
    width: 22.20,
    height: 12.00,
    area: 264.4,
    location: 'Kinmen',
    locationZh: '金門',
    region: 'East'
  },

  // --- Historical ---
  {
    id: 'h-01',
    name: '美麗新淡海(暫停營業)',
    nameEn: 'Miranew Danhai (Suspended)',
    type: '1廳(雷射)',
    typeEn: 'Hall 1 (Laser)',
    audio: 'Dolby Atmos',
    width: 25.00,
    height: 13.50,
    area: 337.5,
    location: 'New Taipei',
    locationZh: '新北',
    region: 'Historical'
  },
  {
    id: 'h-02',
    name: '國立海洋科技博物館(舊)',
    nameEn: 'NMMST (Old Screen)',
    type: 'IMAX(已改裝)*',
    typeEn: 'IMAX (Renovated)*',
    audio: '-',
    width: 28.40,
    height: 22.00,
    area: 624.8,
    location: 'Keelung',
    locationZh: '基隆',
    region: 'Historical'
  },
  {
    id: 'h-03',
    name: '台北日新威秀(已歇業)',
    nameEn: 'Vieshow Sun (Closed)',
    type: 'IMAX',
    typeEn: 'IMAX',
    audio: '-',
    width: 21.10,
    height: 11.30,
    area: 238.43,
    location: 'Taipei',
    locationZh: '台北',
    region: 'Historical'
  },
  {
    id: 'h-04',
    name: '台中老虎城威秀(舊)',
    nameEn: 'Vieshow Tiger City (Old)',
    type: 'IMAX(已改裝)',
    typeEn: 'IMAX (Renovated)',
    audio: '-',
    width: 15.40,
    height: 8.60,
    area: 132.44,
    location: 'Taichung',
    locationZh: '台中',
    region: 'Historical'
  },
  {
    id: 'h-05',
    name: '台中新光(舊)',
    nameEn: 'Shin Kong Taichung (Old)',
    type: '1廳(已改裝)',
    typeEn: 'Hall 1 (Renovated)',
    audio: 'Dolby Atmos',
    width: 15.50,
    height: 6.60,
    area: 102.3,
    location: 'Taichung',
    locationZh: '台中',
    region: 'Historical'
  },
  {
    id: 'h-06',
    name: '台中華威(已易主)',
    nameEn: 'Wovie Cinemas (Rebranded)',
    type: '1廳',
    typeEn: 'Hall 1',
    audio: 'Dolby Atmos',
    width: 14.30,
    height: 6.25,
    area: 89.375,
    location: 'Taichung',
    locationZh: '台中',
    region: 'Historical'
  },
  {
    id: 'h-07',
    name: '岡山秀泰(已改裝)',
    nameEn: 'Showtime Gangshan (Renovated)',
    type: '巨幕廳(已改裝)',
    typeEn: 'Giant Screen (Renovated)',
    audio: 'Dolby 7.1',
    width: 20.00,
    height: 11.00,
    area: 220,
    location: 'Kaohsiung',
    locationZh: '高雄',
    region: 'Historical'
  },
  {
    id: 'h-08',
    name: '夢時代喜滿客(已易主)',
    nameEn: 'Cinemark Dream Mall (Rebranded)',
    type: 'CINE-X(雷射)*',
    typeEn: 'CINE-X (Laser)*',
    audio: '-',
    width: 20.00,
    height: 8.20,
    area: 164,
    location: 'Kaohsiung',
    locationZh: '高雄',
    region: 'Historical'
  },
];

export const HUMAN_HEIGHT = 1.75;